ARG target=centos6
FROM centos:${target} AS stage1

WORKDIR /tmp
RUN yum install -y epel-release \
    && yum groupinstall -y 'Development Tools' \
    && useradd rpmbuild \
    && useradd mockbuild

FROM stage1 AS stage2

ARG target
COPY --chown=rpmbuild:rpmbuild rpmbuild .
RUN ./build.sh --target=${target}

FROM scratch

COPY --from=stage2 /tmp/rpms /rpms
