FROM scratch

ARG arch=x86_64
ARG rootfs=rootfs.tar.gz

ADD ${rootfs} /
WORKDIR /tmp
RUN apk update && apk add alpine-sdk bash
COPY setup.sh .
RUN ./setup.sh && rm -f ./setup.sh

USER build
WORKDIR /home/build

ENTRYPOINT ["/bin/bash"]
